// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDbjQm3yD7KNbV96j6cHpgXU4NeYdYgUM',
    appId: '1:887366055872:web:04b927809f939cfa7f3a25',
    messagingSenderId: '887366055872',
    projectId: 'list-it-ff827',
    authDomain: 'list-it-ff827.firebaseapp.com',
    storageBucket: 'list-it-ff827.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk8CBPni-be-HVR_2fTUHOPNcc39wNku8',
    appId: '1:887366055872:android:fb4be3cf492448e57f3a25',
    messagingSenderId: '887366055872',
    projectId: 'list-it-ff827',
    storageBucket: 'list-it-ff827.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNlALxbStPtJFscloAobf6LGH3p89WkCU',
    appId: '1:887366055872:ios:486136ce50f6b1507f3a25',
    messagingSenderId: '887366055872',
    projectId: 'list-it-ff827',
    storageBucket: 'list-it-ff827.appspot.com',
    iosBundleId: 'com.example.listIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNlALxbStPtJFscloAobf6LGH3p89WkCU',
    appId: '1:887366055872:ios:a5fd62cd3e0450317f3a25',
    messagingSenderId: '887366055872',
    projectId: 'list-it-ff827',
    storageBucket: 'list-it-ff827.appspot.com',
    iosBundleId: 'com.example.listIt.RunnerTests',
  );
}
